#!/bin/bash

# Based on
# https://github.com/ordanax/arch2018
# https://github.com/Antidote1911/packarch_installer

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

echo "${red}Autoinstall ArchLinux"
echo "Empty /dev/sda required."
echo "Script will create:"
echo "/dev/sda1 for boot"
echo "/dev/sda2 for root"
echo "/dev/sda3 for home"
echo "WARNING! All data on /dev/sda will be deleted.${reset}"
read -p "Continue ? (Y,n)" continue

mount -o remount,size=2G /run/archiso/cowspace
timedatectl set-ntp true

read -p "hostname: " hostname
##########################################
read -p "username: " username
read -p "$username Password: " user_pass
echo "${green}Same password will be for root user${reset}"
##########################################

echo "Install to virtualbox ?"
read -p "1 - yes, 0 - no: " vm_setting

echo "Select desktop:"
read -p "0 Xfce antidote, 1 Xfce base, 2 Plasma, 3 Bspwm: " desktop_setting

cat <<EOF | fdisk /dev/sda
o
n
p


+400M
Y
n
p


+30G
Y
n
p



Y
a
1
w
EOF
partprobe

yes | mkfs.ext4 /dev/sda1
yes | mkfs.ext4 /dev/sda2
yes | mkfs.ext4 /dev/sda3


echo "${green}Mount partitions${reset}"
mount /dev/sda2 /mnt
mkdir /mnt/{boot,home}
mount /dev/sda1 /mnt/boot
mount /dev/sda3 /mnt/home

echo "${green}Make swap${reset}"
fallocate -l 4G /mnt/swapfile
chmod 600 /mnt/swapfile
mkswap /mnt/swapfile
swapon --discard /mnt/swapfile

echo "${green}Get the fastest pacman mirrors ${reset}"
pacman -Sy --noconfirm reflector || { echo "Error at script start: Are you sure you're running this as the root user? Are you sure you have an internet connection?"; exit; }
cp -vf /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
reflector --country Netherlands --country Russia -p https --sort rate --verbose --save /etc/pacman.d/mirrorlist

echo "${green}Install ArchLinux${reset}"
pacstrap /mnt base base-devel linux

echo "${green}Generation fstab${reset}"
genfstab -pU /mnt >> /mnt/etc/fstab
echo '/swapfile none swap defaults,discard 0 0' >> /mnt/etc/fstab

arch-chroot /mnt sh -c 'echo '$hostname' > /etc/hostname'
arch-chroot /mnt rm -f /etc/hosts
arch-chroot /mnt sh -c "echo "127.0.0.1		localhost" >> /etc/hosts"
arch-chroot /mnt sh -c "echo "::1		    localhost" >> /etc/hosts"
arch-chroot /mnt sh -c "echo "127.0.1.1		"$hostname".localdomain "'$hostname' >> /etc/hosts"
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
echo "${green}Set locale${reset}"
arch-chroot /mnt sh -c 'echo "en_US.UTF-8 UTF-8" > /etc/locale.gen'
arch-chroot /mnt sh -c 'echo "ru_RU.UTF-8 UTF-8" > /etc/locale.gen'
arch-chroot /mnt locale-gen
arch-chroot /mnt hwclock --systohc --localtime
arch-chroot /mnt sh -c "echo "LANG=en_US.UTF-8" > /etc/locale.conf"
arch-chroot /mnt sh -c "echo "KEYMAP=ru" > /etc/vconsole.conf"
arch-chroot /mnt sh -c "echo "FONT=ter-u14n" >> /etc/vconsole.conf"
arch-chroot /mnt mkinitcpio -p linux
arch-chroot /mnt pacman -Syy
arch-chroot /mnt pacman -S grub --noconfirm
arch-chroot /mnt grub-install --recheck --target=i386-pc /dev/sda
arch-chroot /mnt sed -i -e 's/^GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=1/' /etc/default/grub
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

arch-chroot /mnt sh -c 'echo "root:'$user_pass'" | chpasswd'
arch-chroot /mnt sh -c 'echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
arch-chroot /mnt useradd -m -g users -G "adm,audio,floppy,log,network,rfkill,scanner,storage,optical,power,wheel" -s /bin/bash $username
arch-chroot /mnt sh -c 'echo "'$username':'$user_pass'" | chpasswd'
arch-chroot /mnt systemctl set-default -f graphical.target

########## Xorg and common packages ###########
echo "${green}Install common packs${reset}"
arch-chroot /mnt pacman -S - < common_pkg.txt --noconfirm

arch-chroot /mnt git clone https://github.com/slider23/packarch_installer.git

arch-chroot /mnt mkdir /usr/share/backgrounds
arch-chroot /mnt cp -r /packarch_installer/config/backgrounds/packarch /usr/share/backgrounds/
arch-chroot /mnt cp -r /packarch_installer/config/packarch-icon.png /usr/share/pixmaps/packarch-icon.png
arch-chroot /mnt cp -r /packarch_installer/config/00-keyboard.conf /etc/X11/xorg.conf.d/00-keyboard.conf
arch-chroot /mnt cp -r /packarch_installer/config/makepkg /usr/bin/makepkg
#arch-chroot /mnt wget -q -4 --no-check-certificate -O /usr/bin/makepkg https://raw.githubusercontent.com/Antidote1911/packarch/master/airootfs/usr/bin/makepkg
echo "${green}Install yay${reset}"
arch-chroot /mnt sh -c "cd ~ && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm && cd .. && rm -rf yay"

############# Aur common packages #########################
#arch-chroot /mnt sudo -u $username yay -S --noconfirm fetchmirrors
#arch-chroot /mnt gpg --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
#arch-chroot /mnt sudo -u $username yay -S --noconfirm dropbox
#arch-chroot /mnt gpg --recv-keys 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
#arch-chroot /mnt sudo -u $username yay -S --noconfirm spotify
#######################################

if [[ $desktop_setting == 0 ]]; then
  echo "${green}Install packs for Xfce Antidote${reset}"
  arch-chroot /mnt pacman -S - < xfce_antidote_pkg.txt --noconfirm
  arch-chroot /mnt sudo -u $username yay -S --noconfirm pamac-aur
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-icon-theme-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-circle-icon-theme-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-circle-arc-icons-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-folders-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm mintstick-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm libgksu
  arch-chroot /mnt sudo -u $username yay -S --noconfirm gksu
  ###### xfce antidote config #########
  #arch-chroot /mnt wget -q -4 --no-check-certificate -O /home/$username/ https://raw.githubusercontent.com/Antidote1911/packarch_installer/master/config_xfce.tar.xz
  arch-chroot /mnt tar -xf /packarch_installer/config/config_xfce.tar.xz -C /home/$username/
  ######    Lightdm config    #########
  arch-chroot /mnt sh -c 'sed -i "s/#greeter-session=example-gtk-gnome.*/greeter-session=lightdm-gtk-greeter/g" /etc/lightdm/lightdm.conf'
  arch-chroot /mnt sh -c 'echo "[greeter]" > /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "theme-name = Arc-Dark" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "icon-theme-name = Numix-Circle" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "background = /usr/share/backgrounds/packarch/7.jpg" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "default-user-image = /usr/share/pixmaps/packarch-icon.png" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "user-background = false" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "screensaver-timeout = 0" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "greeter-setup-script=/usr/bin/numlockx on" >> /etc/lightdm/lightdm.conf'
  arch-chroot /mnt cp -r /packarch_installer/config/environment /etc/environment
  arch-chroot /mnt systemctl enable lightdm.service

elif [[ $desktop_setting == 1 ]]; then
  echo "${green}Install packs for Xfce${reset}"
  arch-chroot /mnt pacman -S - < xfce_base_pkg.txt --noconfirm
  arch-chroot /mnt sudo -u $username yay -S --noconfirm pamac-aur
  arch-chroot /mnt sudo -u $username yay -S --noconfirm libgksu
  arch-chroot /mnt sudo -u $username yay -S --noconfirm gksu
  arch-chroot /mnt systemctl enable lightdm.service

elif [[ $desktop_setting == 2 ]]; then
  echo "${green}Install packs for Plasma${reset}"
  arch-chroot /mnt pacman -S - < plasma_pkg.txt --noconfirm
  arch-chroot /mnt sudo -u $username yay -S --noconfirm pamac-aur
  arch-chroot /mnt sudo -u $username yay -S --noconfirm pamac-tray-appindicator
  arch-chroot /mnt systemctl enable sddm.service

elif [[ $desktop_setting == 3 ]]; then
  echo "${green}Install packs for Bspwm${reset}"
  arch-chroot /mnt pacman -S - < bspwm_pkg.txt --noconfirm
  arch-chroot /mnt sudo -u $username yay -S --noconfirm libgksu
  arch-chroot /mnt sudo -u $username yay -S --noconfirm gksu
  arch-chroot /mnt sudo -u $username yay -S --noconfirm xtitle-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm bspwm-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm polybar
  arch-chroot /mnt sudo -u $username yay -S --noconfirm sardi-icons
  arch-chroot /mnt sudo -u $username yay -S --noconfirm mintstick-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm sutils-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm sxhkd-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm pamac-aur
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-icon-theme-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-circle-icon-theme-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm numix-circle-arc-icons-git
  arch-chroot /mnt sudo -u $username yay -S --noconfirm nerd-fonts-complete
  arch-chroot /mnt sudo -u $username yay -S --noconfirm breeze-cursors-lh
  arch-chroot /mnt sudo -u $username yay -S --noconfirm xcursor-breeze
  arch-chroot /mnt tar -xf /packarch_installer/config/config_bspwm.tar.xz -C /home/$username/
  arch-chroot /mnt tar -xf /packarch_installer/config/oblogout_theme.tar.xz -C /usr/share/themes/
  arch-chroot /mnt cp -r /packarch_installer/config/environment /etc/environment
  arch-chroot /mnt sh -c 'sed -i "s/#greeter-session=example-gtk-gnome.*/greeter-session=lightdm-gtk-greeter/g" /etc/lightdm/lightdm.conf'
  arch-chroot /mnt sh -c 'echo "[greeter]" > /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "theme-name = Arc-Dark" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "icon-theme-name = Numix-Circle" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "background = /usr/share/backgrounds/packarch/7.jpg" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "default-user-image = /usr/share/pixmaps/packarch-icon.png" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "user-background = false" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "screensaver-timeout = 0" >> /etc/lightdm/lightdm-gtk-greeter.conf'
  arch-chroot /mnt sh -c 'echo "greeter-setup-script=/usr/bin/numlockx on" >> /etc/lightdm/lightdm.conf'
  arch-chroot /mnt cp -r /packarch_installer/config/oblogout.conf /etc/oblogout.conf
  arch-chroot /mnt systemctl enable lightdm.service
fi
########## VM or not ###########################
if [[ $vm_setting == 1 ]]; then
  echo "${green}Install packs for Virtualbox${reset}"
  arch-chroot /mnt pacman -S - < virtual_machine_pkg.txt --noconfirm

elif [[ $vm_setting == 0 ]]; then
  echo "${green}Install packs for hardware${reset}"
  arch-chroot /mnt pacman -S - < real_install_pkg.txt --noconfirm
  arch-chroot /mnt cp -r /packarch_installer/config/20-nvidia.conf /etc/X11/xorg.conf.d/20-nvidia.conf
fi
###############################################################################
arch-chroot /mnt systemctl enable NetworkManager
arch-chroot /mnt systemctl enable ntpd.service
exit
